<ul class="space-y-1">
    <?php $role = auth()->user()->role; ?>

    <?php if($role === 'admin'): ?>
        <li><a href="<?php echo e(route('admin.dashboard')); ?>" class="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium <?php echo e(request()->routeIs('admin.dashboard') ? 'bg-indigo-50 text-indigo-700' : 'text-gray-600 hover:bg-gray-100'); ?>"><i class="fa-solid fa-gauge w-4"></i> Dashboard</a></li>
        <li><a href="<?php echo e(route('admin.users.index')); ?>" class="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium <?php echo e(request()->routeIs('admin.users*') ? 'bg-indigo-50 text-indigo-700' : 'text-gray-600 hover:bg-gray-100'); ?>"><i class="fa-solid fa-users w-4"></i> Management User</a></li>
        <li><a href="<?php echo e(route('admin.profile')); ?>" class="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium <?php echo e(request()->routeIs('admin.profile') ? 'bg-indigo-50 text-indigo-700' : 'text-gray-600 hover:bg-gray-100'); ?>"><i class="fa-solid fa-user w-4"></i> Profile</a></li>
    <?php elseif($role === 'manager'): ?>
        <li><a href="<?php echo e(route('manager.dashboard')); ?>" class="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium <?php echo e(request()->routeIs('manager.dashboard') ? 'bg-indigo-50 text-indigo-700' : 'text-gray-600 hover:bg-gray-100'); ?>"><i class="fa-solid fa-gauge w-4"></i> Dashboard</a></li>
        <li><a href="<?php echo e(route('manager.review.index')); ?>" class="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium <?php echo e(request()->routeIs('manager.review*') ? 'bg-indigo-50 text-indigo-700' : 'text-gray-600 hover:bg-gray-100'); ?>"><i class="fa-solid fa-clipboard-check w-4"></i> Review KPI</a></li>
        <li><a href="<?php echo e(route('manager.profile')); ?>" class="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium <?php echo e(request()->routeIs('manager.profile') ? 'bg-indigo-50 text-indigo-700' : 'text-gray-600 hover:bg-gray-100'); ?>"><i class="fa-solid fa-user w-4"></i> Profile</a></li>
    <?php elseif($role === 'lead_hr'): ?>
        <li><a href="<?php echo e(route('leadhr.dashboard')); ?>" class="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium <?php echo e(request()->routeIs('leadhr.dashboard') ? 'bg-indigo-50 text-indigo-700' : 'text-gray-600 hover:bg-gray-100'); ?>"><i class="fa-solid fa-gauge w-4"></i> Dashboard</a></li>
        <li><a href="<?php echo e(route('leadhr.kpi.index')); ?>" class="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium <?php echo e(request()->routeIs('leadhr.kpi*') ? 'bg-indigo-50 text-indigo-700' : 'text-gray-600 hover:bg-gray-100'); ?>"><i class="fa-solid fa-file-alt w-4"></i> Form KPI</a></li>
        <li><a href="<?php echo e(route('leadhr.review.index')); ?>" class="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium <?php echo e(request()->routeIs('leadhr.review*') ? 'bg-indigo-50 text-indigo-700' : 'text-gray-600 hover:bg-gray-100'); ?>"><i class="fa-solid fa-clipboard-check w-4"></i> Review KPI</a></li>
        <li><a href="<?php echo e(route('leadhr.profile')); ?>" class="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium <?php echo e(request()->routeIs('leadhr.profile') ? 'bg-indigo-50 text-indigo-700' : 'text-gray-600 hover:bg-gray-100'); ?>"><i class="fa-solid fa-user w-4"></i> Profile</a></li>
    <?php elseif($role === 'lead'): ?>
        <li><a href="<?php echo e(route('lead.dashboard')); ?>" class="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium <?php echo e(request()->routeIs('lead.dashboard') ? 'bg-indigo-50 text-indigo-700' : 'text-gray-600 hover:bg-gray-100'); ?>"><i class="fa-solid fa-gauge w-4"></i> Dashboard</a></li>
        <li><a href="<?php echo e(route('lead.kpi.index')); ?>" class="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium <?php echo e(request()->routeIs('lead.kpi*') ? 'bg-indigo-50 text-indigo-700' : 'text-gray-600 hover:bg-gray-100'); ?>"><i class="fa-solid fa-file-alt w-4"></i> Form KPI</a></li>
        <li><a href="<?php echo e(route('lead.review.index')); ?>" class="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium <?php echo e(request()->routeIs('lead.review*') ? 'bg-indigo-50 text-indigo-700' : 'text-gray-600 hover:bg-gray-100'); ?>"><i class="fa-solid fa-clipboard-check w-4"></i> Review KPI</a></li>
        <li><a href="<?php echo e(route('lead.profile')); ?>" class="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium <?php echo e(request()->routeIs('lead.profile') ? 'bg-indigo-50 text-indigo-700' : 'text-gray-600 hover:bg-gray-100'); ?>"><i class="fa-solid fa-user w-4"></i> Profile</a></li>
    <?php elseif($role === 'principle'): ?>
        <li><a href="<?php echo e(route('principle.dashboard')); ?>" class="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium <?php echo e(request()->routeIs('principle.dashboard') ? 'bg-indigo-50 text-indigo-700' : 'text-gray-600 hover:bg-gray-100'); ?>"><i class="fa-solid fa-gauge w-4"></i> Dashboard</a></li>
        <li><a href="<?php echo e(route('principle.kpi.index')); ?>" class="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium <?php echo e(request()->routeIs('principle.kpi*') ? 'bg-indigo-50 text-indigo-700' : 'text-gray-600 hover:bg-gray-100'); ?>"><i class="fa-solid fa-file-alt w-4"></i> Form KPI</a></li>
        <li><a href="<?php echo e(route('principle.profile')); ?>" class="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium <?php echo e(request()->routeIs('principle.profile') ? 'bg-indigo-50 text-indigo-700' : 'text-gray-600 hover:bg-gray-100'); ?>"><i class="fa-solid fa-user w-4"></i> Profile</a></li>
    <?php else: ?>
        <li><a href="<?php echo e(route('employee.dashboard')); ?>" class="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium <?php echo e(request()->routeIs('employee.dashboard') ? 'bg-indigo-50 text-indigo-700' : 'text-gray-600 hover:bg-gray-100'); ?>"><i class="fa-solid fa-gauge w-4"></i> Dashboard</a></li>
        <li><a href="<?php echo e(route('employee.kpi.index')); ?>" class="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium <?php echo e(request()->routeIs('employee.kpi*') ? 'bg-indigo-50 text-indigo-700' : 'text-gray-600 hover:bg-gray-100'); ?>"><i class="fa-solid fa-file-alt w-4"></i> Form KPI</a></li>
        <li><a href="<?php echo e(route('employee.profile')); ?>" class="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium <?php echo e(request()->routeIs('employee.profile') ? 'bg-indigo-50 text-indigo-700' : 'text-gray-600 hover:bg-gray-100'); ?>"><i class="fa-solid fa-user w-4"></i> Profile</a></li>
    <?php endif; ?>
</ul>
<?php /**PATH D:\New folder (20)\kpi-system\resources\views/layouts/sidebar.blade.php ENDPATH**/ ?>